// Generated by https://quicktype.io

export interface TopLevel {
  archetype:  Archetype;
  card:       Card;
  collection: Collection;
  deck:       Deck;
  set:        Set;
  user:       User;
}

export interface Archetype {
  color_identity: string;
  created:        string;
  deck:           string;
  format:         string;
  key:            string;
  promoted:       string;
}

export interface Card {
  id:                number;
  oracle_id:         number;
  prints_search_uri: string;
  rulings_uri:       string;
  scryfall_uri:      string;
  uri:               string;
}

export interface Collection {
  alias:      string;
  card_count: number;
  created:    string;
  id:         number;
  modified:   string;
  owner:      number;
}

export interface Deck {
  format: string;
  froze:  boolean;
  key:    string;
  legal:  boolean;
  name:   string;
  owner:  string;
}

export interface Set {
  block:           string;
  block_code:      string;
  card_count:      number;
  code:            string;
  digital:         boolean;
  foil_only:       string;
  icon_svg_uri:    string;
  mtgo_code:       string;
  name:            string;
  parent_set_code: string;
  released_at:     number;
  search_uri:      string;
  set_type:        string;
}

export interface User {
  key:        string;
  last_login: string;
  mail:       string;
  online:     boolean;
  passw:      string;
  user_age:   string;
  username:   string;
}
